### ISSUE TITLE
Configuration parameters are described as nested JSON objects

### ISSUE THREAD

**Issue by awendelin-work** [eclipse-cdt-cloud/trace-server-protocol#123]
### Bug Description:

The endpoints to create a derived output using a set of schema-specified parameters describe the "parameters" object as only being allowed to contain other JSON objects rather than any kind of JSON value.

The specific yaml descriptions that are an issue are OutputConfigurationQueryParameters and Configuration which describes the parameters as:

```yaml
        parameters:
          type: object
          additionalProperties:
            type: object
            description: Parameters as specified in the schema or list of ConfigurationParameterDescriptor
              of the corresponding ConfigurationTypeDescriptor.
          description: Parameters as specified in the schema or list of ConfigurationParameterDescriptor
            of the corresponding ConfigurationTypeDescriptor.
```

This specification only allows a JSON where each of "parameters" keys has a JSON object as a value like:
```json
"parameters": {
    "asdf": {"test": 12}
}
```
and would disallow a JSON where "asdf" has any other type like:
```json
"parameters": {
    "asdf": 12
}
```

This also goes against the provided example, which is disallowed by the current schema (since neither "threads" or "cpus" have a JSON object as a value):
```json
{
  "name": "Follow My-thread",
  "description": "My-thread on even CPUs",
  "typeId": "my.config.source.type.id",
  "parameters": {
    "threads": "My-thread",
    "cpus": [
      0,
      2,
      4,
      6
    ]
  }
}
```
